# 빌드 환경 설정
FROM maven:3.6-jdk-11
WORKDIR /app

# pom.xml과 src/ 디렉터리 복사
COPY pom.xml .
COPY src ./src

# application build
RUN mvn clean package

# 빌드된 JAR 파일을 실행 환경으로 복사
RUN cp /app/target/*.jar ./app.jar

# application run
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]