FROM node:14

WORKDIR /app

# COPY ./ /
# WORKDIR로 /app 위치로 이동하기 때문에
# COPY의 위치도 변경해줬다.
COPY . . 


RUN npm install

USER node

EXPOSE 3000


# ENTRYPOINT npm 설정으로 인해 실행되는 명령어에 npm이 기본으로 붙는다
ENTRYPOINT ["npm"]

# ENTRYPOINT npm 설정으로 인해 npm 생략
# CMD ["npm", "start"]
CMD ["start"]