version: '3'
services:
  leafy-postgres:
    image: devwikirepo/leafy-postgres:1.0.0
  leafy-backend:
    build: ./leafy-backend
    image: leafy-backend:5.0.0-compose
    environment:
    - DB_URL=leafy-postgres
    # depends_on에 작성된 컨테이너가 실행될 때 까지, 컨테이너 실행을 보류한다.
    depends_on:
      - leafy-postgres
  leafy-front:
    build: ./leafy-frontend
    image: leafy-front:5.0.0-compose
    environment:
      - BACKEND_HOST=leafy-backend
    ports:
      - 80:80
    depends_on:
      - leafy-backend