- hosts: all
#   become: true

  tasks:
  - name: create a docker image with deployed waf file
    command: docker build -t april2nd/cicd-project-ansible .
    args:
        chdir: /root

  - name: push the image on Docker Hub
    command: docker push april2nd/cicd-project-ansible

  - name: remove the docker image from the ansible server
    command: docker rmi april2nd/cicd-project-ansible
    ignore_errors: yes
